# Generated by Django 2.2.4 on 2020-11-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotipyAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixtape',
            name='spotify_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
