# Generated by Django 2.2.4 on 2020-11-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotipyAuthApp', '0002_mixtape_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixtape',
            name='burned_by',
            field=models.ManyToManyField(related_name='mixtape_burned', to='spotipyAuthApp.User'),
        ),
        migrations.AddField(
            model_name='mixtape',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
