# Generated by Django 2.2.4 on 2020-11-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotipyAuthApp', '0003_auto_20201120_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
