# Generated by Django 2.2.4 on 2020-11-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotipyAuthApp', '0004_auto_20201120_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixtape',
            name='shared_with',
            field=models.ManyToManyField(related_name='mixtapes_shared', to='spotipyAuthApp.User'),
        ),
        migrations.AlterField(
            model_name='mixtape',
            name='burned_by',
            field=models.ManyToManyField(related_name='mixtapes_burned', to='spotipyAuthApp.User'),
        ),
    ]
